version: "3"
services: 
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: es01
    environment: 
      - "http.host=0.0.0.0"
      - "transport.host=localhost"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt"
      - "xpack.security.http.ssl.certificate=$CERTS_DIR/es01/es01.crt"
      - "xpack.security.http.ssl.key=$CERTS_DIR/es01/es01.key"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      # mount custom config
      - "./elasticsearch-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./certs:$CERTS_DIR"
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: es02
    environment: 
      # - "http.host=0.0.0.0"
      # - "transport.host=localhost"
      # - "discovery.type=single-node"
      - node.name=es02
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt"
      - "xpack.security.http.ssl.certificate=$CERTS_DIR/es01/es01.crt"
      - "xpack.security.http.ssl.key=$CERTS_DIR/es01/es01.key"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      # mount custom config
      - "./elasticsearch-node.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./certs:$CERTS_DIR"
    ports:
      - 9200:9200
    networks:
      - elastic
  kib01:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://es01:9200
      - ELASTICSEARCH_HOSTS=["http://es01:9200"]
      - elasticsearch.username=kibana
      - elasticsearch.password=Passw0rd!!
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic
      
volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  elastic:
    driver: bridge